# Generated by Django 5.1.6 on 2025-02-14 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Comma separated list of symptoms')),
                ('result', models.TextField(help_text='Results from AI analysis')),
                ('probability_score', models.FloatField(help_text='Probability score of the result')),
                ('description', models.TextField(help_text='Detailed description of the AI results')),
                ('precautions', models.TextField(help_text='Precautions based on the result')),
                ('image', models.ImageField(blank=True, help_text='Image if available', null=True, upload_to='ai_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
