# Generated by Django 5.1.6 on 2025-03-03 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='probability_score',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='result',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='disease',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='probability',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='precautions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
