# Generated by Django 5.1.6 on 2025-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0003_alter_aimodel_description_alter_aimodel_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='source',
            field=models.CharField(choices=[('text', 'Text Analysis'), ('image', 'Image Analysis')], default='text', max_length=5),
        ),
    ]
