# Generated by Django 5.1.6 on 2025-03-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_remove_aimodel_probability_score_and_more'),
        ('ai_reports', '0007_alter_report_generated_by_alter_report_patient'),
        ('prescriptions', '0002_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model', to='ai_models.aimodel'),
        ),
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescriptions.prescription'),
        ),
    ]
