# Generated by Django 5.1.6 on 2025-03-08 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0003_alter_aimodel_description_alter_aimodel_probability'),
        ('ai_reports', '0008_alter_report_ai_model_alter_report_prescription'),
        ('prescriptions', '0003_alter_prescription_doctor_alter_prescription_dosage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_models.aimodel'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(default=16, limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
