# Generated by Django 5.1.6 on 2025-03-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0003_alter_aimodel_description_alter_aimodel_probability'),
        ('ai_reports', '0010_alter_report_status'),
        ('prescriptions', '0003_alter_prescription_doctor_alter_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_models.aimodel'),
        ),
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
