# Generated by Django 5.1.6 on 2025-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('approval_status_patient', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('declined', 'Declined')], default='waiting', max_length=20)),
                ('approval_status_doctor', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('declined', 'Declined')], default='waiting', max_length=20)),
            ],
        ),
    ]
