# Generated by Django 5.1.6 on 2025-04-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_fee_doctoravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='fee',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
    ]
